var lang_var = {};
var lang_cn = {
	code_lab:{
		YES:"是", NO:"否", TIP:"提示~", ERROR_1:"加载数据似乎出现问题了，请刷新。",
		OPEN_LINK:"打开商品链接？", OKING_TIP:"提交中..."
	},
	tab_menu_lab:{
		mission:"任务",
		me:"我的",
		appname:"Make Money",
		mission_catg_items_shopee:"[平台一]",  
		mission_catg_items_lazada:"[平台二]",
		mission_catg_items_amazon:"[平台三]",
	},
	tab_menu:{
		me:{
			lab:{
				member:"成员",
				user_email:"用户邮箱",
				total_commission:"您的佣金",
				commission:"佣金",
				principal:"总本金",
				dayreward:"每日任务奖励", reward:"奖励", dayreward_explain:"每日任务奖励说明<br/>警告：每一样产品3天内只能购买一次。否则每日奖励取消。",
				mission_list_bottom_desc:"欲了解更多产品，请点击任何产品链接到主页。",
				interest:"总利息",
				commission_team:"团队佣金",
				is_draw_money_total:"可提现金额",
				public_notice:"公告",
				capital_details:"我的订单",
				my_business_partner:"我的团队",
				share_make_money:"招募员工",
				copy_tip:"复制",
				copy_link_tip:"复制链接->发送给您的亲朋好友",
				copy_link_tip2:"复制链接",
				copy_link_tip3:"复制成功",
				draw_money:"提现",
				confri_tip:"确认",
				customer_service:"客服",
				help:"帮助",
				forget_passwd:"忘记密码",
				logout:"退出登录",
				mission_item_stock_tip:"库存",
				mission_note:"任务说明：<br/>&nbsp;&nbsp;&nbsp;&nbsp;1.根据下面的任务列表选择您要购买的商品，您将被重新定位到商品页面，根据操作进行购买可以获得相应的佣金。<br/>&nbsp;&nbsp;&nbsp;&nbsp;2.每款商品3天内只能购买一次。<br/>&nbsp;&nbsp;&nbsp;&nbsp;3.请确保您为商品填写的电子邮件地址与【Make money】电子邮件相同。<br/>&nbsp;&nbsp;&nbsp;&nbsp;4.购买商品后的第三天你需要确认收货，并给予良好的评价，货款和佣金将立即到帐。<br/>&nbsp;&nbsp;&nbsp;&nbsp;5.如果您取消订单、申请退款、申请退货，那么您无法得到佣金和利息。",
				help_note:"1. 我们会为您订单费用计算利息，例如：订单金额$20，佣金为$2，每日利息为$20+$2=$22*0.00006323=$0.00139106 (即使您什么都不做，您每日也能得到$0.00139106)<br/>2. 团队的佣金奖励不计算利息。<br/>3.完成的订单既可以提现又可以兑换优惠券。若已提现的订单则没有此功能。<br/>4.每日任务奖励：2日后（即第三天完成订单后会发放奖励)",
				order_status:"订单状态",
				total_money:"金额",
				amounts_tip:"钱",
				drawmone_100_tip:"由于USDT手续费很贵，我们设定为$100.00以上才能提现",
				order_total_interest:"订单利息",
				order_total_cut:"抽成",
				order_draw_money_status:"提现状态",
				draw_money_ok:"可以提现",
				draw_money_verifing:"审核中",
				draw_money_verify_passport:"通过审核",
				draw_money_verify_decline:"已拒绝",
				draw_money_wait_completed:"等待完成",
				draw_money_help_tip:"1. 我们采用更加安全的比特币交易方式，因此，需要由客户自行承担提款手续费。<br/>2. 每次提款需要满足至少100美金的整数。<br/>具体提款手续费，以比特币平台实际为准，可以向客户服务进行咨询。谢谢您的理解！",
				share_make_money_fxnote:'<font color="#0062CC"><b>B</b></font>是<font color="#ee0053"><b>您</b></font>的员工<br/><font color="#f4a300"><b>C</b></font>是<font color="#0062CC"><b>B</b></font>的员工<br/><font color="#aa00ff"><b>D</b></font>是<font color="#f4a300"><b>C</b></font>的员工<br/>我们会赠送额外的佣金给您（不会减少任何一位员工的钱）<br/>(1). <font color="#0062CC"><b>B</b></font>佣金的<font color="#00b020"><b>35%</b></font>归属于您。<br/>(2). <font color="#f4a300"><b>C</b></font>佣金的<font color="#00b020"><b>15%</b></font>归属于您。<br/>(3). <font color="#aa00ff"><b>D</b></font>佣金的<font color="#00b020"><b>5%</b></font>归属于您。<br/>注：团队佣金不计算利息。',
				please_go_exec_mission:'请您先去执行任务。',
				ok_paypal_to_server:"提交USDT-ERC20钱包地址", Please_Input_Paypal_Account:"请输入USDT-ERC20钱包地址",Please_Input_NewPaypal_Account:"请输入新的USDT-ERC20钱包地址",
				ok_isdraw_money_to_paypal:"提现到USDT-ERC20钱包", please_input_confri_data:"请填写正确的字符", ok_draw_money_complete:"请耐心等待管理员审核。",
				TIP_NOT_MONEY_DRAW:"没有可提现的余额", TIP_MONEY_DRAW_TIME:"提现时间:周二和周五", again_onec_buy:"兑换优惠券", coupons_tip:"优惠券", copy_coupons_tip:"复制优惠券", split_coupons_tip:"拆分优惠券",
				again_onec_buy_help_tip:"将该订单的金额转换为优惠码，使用优惠码可以抵消新订单的金额。是否需要兑换优惠券？",
				DAY_ORDER_Total:"每日完成的订单总数", ORDER_COMPLETE_Total:"完成的订单数", ORDER_OTHER_Total:"其他的订单数", DATE_TIP:"日期", MISSION_Progress_TIP:"进度度", WAIT_COMPLETE_TIP:"等待完成",
				COMMENT_TIP:"请输入评论内容", Submit_COMMENTS_TIP:"提交评论", COMMENTS_NOT_NULL:"评论不能为空",
				split_coupons_desc:"生成一个新的优惠券，金额必须少于{money}",
				coupons_use_help_tip:"复制优惠券->进入购物车->使用优惠券",
			}
		}
	},
	
};

var lang_en = {
	code_lab:{
		YES:"YES", NO:"NO", TIP:"Tip~", ERROR_1:"There seems to be a problem loading data, please refresh.",
		OPEN_LINK:"Open product link？", OKING_TIP:"submitting..."
	},
	tab_menu_lab:{
		mission:"Task",
		me:"Me",
		appname:"Make Money",
		mission_catg_items_shopee:"[Platform 1]",
		mission_catg_items_lazada:"[Platform 2]",
		mission_catg_items_amazon:"[Platform 3]",
	},
	tab_menu:{
		me:{
			lab:{
				member:"Member",
				user_email:"User Email",
				total_commission:"Personal Commission",
				commission:"Commission",
				principal:"The Principal",
				dayreward:"Daily task reward", reward:"Reward", dayreward_explain:"Daily task reward description<br/>Warning: Each product can only be purchased once within 3 days.Otherwise, the daily bonus will be cancelled.",
				mission_list_bottom_desc:"For more products, please click on any product link to the homepage.",
				interest:"Total Interest",
				commission_team:"Team Commission",
				is_draw_money_total:"Account Withdrawal",
				public_notice:"Notice",
				capital_details:"My Order",
				my_business_partner:"My Team",
				share_make_money:"Recruit Staff",
				copy_tip:"Copy",
				copy_link_tip:"Copy link -> send to your relatives and friends",
				copy_link_tip2:"Copy link",
				copy_link_tip3:"Copy successfully",
				draw_money:"Account Withdrawal",
				confri_tip:"Confirm",
				customer_service:"Customer Service",
				help:"Help",
				forget_passwd:"Change Password",
				logout:"Logout",
				mission_item_stock_tip:"stock",
				mission_note:"Task description: <br/>&nbsp;&nbsp;&nbsp;&nbsp;1.Select the goods you want to buy according to the task list below. You will be repositioned to the product page, and you can get the corresponding Commission according to the operation.<br/>&nbsp;&nbsp;&nbsp;&nbsp;2.Each product can only be purchased once within 3 days.<br/>&nbsp;&nbsp;&nbsp;&nbsp;3.Please make sure that the e-mail address you fill in for the product is the same as the e-mail address of [make money].<br/>&nbsp;&nbsp;&nbsp;&nbsp;4.On the third day after purchasing the goods, you need to confirm the receipt and give a good evaluation. The payment and commission will arrive at the account immediately.<br/>&nbsp;&nbsp;&nbsp;&nbsp;5.If you cancel an order, apply for a refund, or apply for a return, then you will not receive commission and interest.",
				help_note:"1. We will calculate interest for your order fee，E.g：order amount $20，commission $2，Daily interest $20+$2=$22*0.00006323=$0.00139106 (Even if you do nothing, you can get $0.00139106)<br/>2. Does not calculate the team's commission reward interest.<br/>3.The completed order can be withdrawn and exchanged for coupons. This function is not available for orders that have been withdrawn.<br/>4.Daily task rewards: rewards will be issued after the order is completed on the third day.<br/>5.For other questions, please contact customer service.",
				share_make_money_fxnote:'<font color="#0062CC"><b>B</b></font> is <font color="#ee0053"><b>your</b></font> employee.<br/><font color="#f4a300"><b>C</b></font> is <font color="#0062CC"><b>B </b></font>employee.<br/><font color="#aa00ff"><b>D</b></font> is <font color="#f4a300"><b>C </b></font>employee.<br/>We will give you an extra commission (will not reduce any employee\'s money)<br/>(1). <font color="#00b020"><b>35%</b></font> of <font color="#0062CC"><b>B</b></font>\'s commission belongs to you.<br/>(2). <font color="#00b020"><b>15%</b></font> of <font color="#f4a300"><b>C</b></font>\'s commission belongs to you.<br/>(3). &nbsp;&nbsp;<font color="#00b020"><b>5%</b></font> of <font color="#aa00ff"><b>D</b></font>\'s commission belongs to you.<br/>Note: The team commission does not calculate interest.',
				order_status:"Order Status",
				total_money:"Total Money",
				amounts_tip:"Amounts",
				drawmone_100_tip:"Due to the high service charge of usdt, we set it to be more than $100.00 to Account Withdrawal.",
				order_total_interest:"Order Interest",
				order_total_cut:"Commission",
				order_draw_money_status:"Withdrawal Status",
				draw_money_ok:"You can withdraw cash",
				draw_money_verifing:"Under Review",
				draw_money_verify_passport:"Approved",
				draw_money_verify_decline:"Rejected",
				draw_money_wait_completed:"Wait for completion",
				draw_money_help_tip:"1. We adopt a more secure Bitcoin transaction method, so the withdrawal fee shall be borne by the customers themselves.<br/>2. Make a round number of at least $100 per withdrawal.<br/>The specific withdrawal fee is subject to the actual Bitcoin platform, and you can consult the customer service.Thank you for your understanding!",
				please_go_exec_mission:'Please go to the task first.',
				ok_paypal_to_server:"Submit USDT-ERC20 wallet address", Please_Input_Paypal_Account:"please input USDT-ERC20 wallet address",Please_Input_NewPaypal_Account:"please input New USDT-ERC20 wallet address",
				ok_isdraw_money_to_paypal:"Withdraw cash to your USDT-ERC20 wallet address", please_input_confri_data:"Please fill in the correct characters", ok_draw_money_complete:"Please wait patiently for the administrator review.",
				TIP_NOT_MONEY_DRAW:"There is no cash balance", TIP_MONEY_DRAW_TIME:"Withdrawal time: Tuesday、Friday", again_onec_buy:"Exchange Coupons", coupons_tip:"Coupons", copy_coupons_tip:"Copy Coupons", split_coupons_tip:"Split Coupons",
				again_onec_buy_help_tip:"Convert the amount of the order into a discount code, which can be used to offset the amount of the new order. Do you need to exchange coupons?？",
				DAY_ORDER_Total:"The total number of orders completed per day", ORDER_COMPLETE_Total:"Number of completed orders", ORDER_OTHER_Total:"Other orders", DATE_TIP:"DATE",
				MISSION_Progress_TIP:"Reward Progress", WAIT_COMPLETE_TIP:"Wait for completion",
				COMMENT_TIP:"Please enter comments", Submit_COMMENTS_TIP:"Submit comments", COMMENTS_NOT_NULL:"Please enter comments",
				split_coupons_desc:"To generate a new coupon, the amount must be less than {money}",
				coupons_use_help_tip:"Copy coupons -> enter shopping cart->use coupons",
			}
		}
	},
	
};